repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0  # バージョンを最新のものに更新
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.2
  hooks:
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
    - id: mypy
      args: [--ignore-missing-imports, --show-column-numbers]
